server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/db
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guiguxiaozhi?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#集成阿里通义千问-通用文本向量-v3

langchain4j:
  community:
    dashscope:
      streaming-chat-model:
        api-key: ${DASH_SCOPE_API_KEY}
        model-name: qwen-plus
      embedding-model:
        api-key: ${DASH_SCOPE_API_KEY}
        model-name: text-embedding-v3
  open-ai:
    chat-model:
      model-name: qwen-max
#      base-url: http://127.0.0.1:11434
      log-responses: true
      log-requests: true
      api-key: ${DASH_SCOPE_API_KEY}

logging:
  level:
    root: info

