server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/db


langchain4j:
  open-ai:
    chat-model:
      model-name: qwen-max
#      base-url: http://127.0.0.1:11434
      log-responses: true
      log-requests: true
      api-key: ${DASH_SCOPE_API_KEY}

logging:
  level:
    root: info

